FROM registry.redhat.io/rhel8/httpd-24
MAINTAINER Vjeko <vjekoslav.aleksic@gmail.com>
LABEL description="image for apache server customized for presentation"
EXPOSE 8080
ENV MESSAGE="How are you?"
RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf
RUN echo  "Date of container build: "$(date) >> /var/www/html/index.html &&\
    echo  "<br>Hello to the Conference!" >> /var/www/html/index.html &&\
    echo "<br>"$MESSAGE >> /var/www/html/index.html
